[pytest]
addopts = --strict-markers --tb=short -v
markers =
    auth: auth tests
    cart: cart tests
    catalog: catalog tests
    register: register tests
    bug: skipped test
    smoke: critical tests
    negative: negative tests

